/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHAT_H_RPCGEN
#define _CHAT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define CHATPROGRAM 0x31234567
#define CHATVERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define STDIN 1
extern  int * write_1(char **, CLIENT *);
extern  int * write_1_svc(char **, struct svc_req *);
#define getChat 2
extern  char ** getchat_1(void *, CLIENT *);
extern  char ** getchat_1_svc(void *, struct svc_req *);
extern int chatprogram_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define STDIN 1
extern  int * write_1();
extern  int * write_1_svc();
#define getChat 2
extern  char ** getchat_1();
extern  char ** getchat_1_svc();
extern int chatprogram_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CHAT_H_RPCGEN */
